使用 scikit-learn 內建資料集 Iris（鳶尾花）針對花萼、花蕊的長寬進行花朵類別判別（setosa 山鳶尾、versicolor 變色鳶尾、virginica 維吉尼亞鳶尾）。此資料集中已標註好每筆資料對應的鳶尾花種類，可視為多類別分類問題（multi-classification）

In [5]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

#獲取資料&探索性資料分析

irisRaw = datasets.load_iris()
print irisRaw.keys() # 印出 key 值，列出有哪些值

['target_names', 'data', 'target', 'DESCR', 'feature_names']


In [6]:
#印出 feature 值
print irisRaw.data

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
# 印出目標標籤，三種花的類別：['setosa':0 'versicolor':1 'virginica':2]
print irisRaw.target_names


print irisRaw.target

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [36]:
import numpy as np
import pandas as pd

# 將資料轉為 pandas DataFrame格式方便進行操作
# data 為觀察目標變數

df_X = pd.DataFrame(irisRaw.data)

# target 為預測變數
df_Y = pd.DataFrame(irisRaw.target)

#把資料集分為 70% 訓練資料，30% 驗證資料 
X_train, X_test, Y_train, Y_test = train_test_split(df_X, df_Y, test_size=0.3)

print '所有資料集筆數 :',len(df_Y) # 印出所有資料集筆數 :150
print '訓練資料集筆數-X_train :',len(X_train),'訓練資料集筆數-Y_train :',len(Y_train)
print '驗證資料集筆數-X_test :',len(X_test),'驗證資料集筆數-Y_test :',len(Y_test)


所有資料集筆數 : 150
訓練資料集筆數-X_train : 105 訓練資料集筆數-Y_train : 105
驗證資料集筆數-X_test : 45 驗證資料集筆數-Y_test : 45


In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC

# 初始化 LinearSVC
linear_Svc = LinearSVC()

# 使用 fit 來建置模型，其參數接收 training data matrix, testing data array，
# 進行 y_train.values.ravel() Data Frame 轉換

linear_Svc.fit(X_train,Y_train.values.ravel())


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [46]:
# 初始化 KNeighborsClassifier
KNN = KNeighborsClassifier()

# 使用 fit 來建置模型，其參數接收 training data matrix, testing data array，
# 進行 y_train.values.ravel() 轉換

KNN.fit(X_train,Y_train.values.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [52]:
# 使用 X_test 來預測結果
print linear_Svc.predict(X_test)
 #預測準確率
print '預測準確率 : ',linear_Svc.score(X_test,Y_test)


[2 0 2 1 2 0 1 2 2 0 0 2 2 1 0 1 0 2 2 1 0 0 0 2 0 2 2 2 1 0 0 2 0 1 2 2 1
 0 2 1 0 2 2 2 1]
預測準確率 :  1.0


In [53]:
print KNN.predict(X_test)
print '預測準確率 :',KNN.score(X_test,Y_test)

[2 0 2 1 2 0 2 2 2 0 0 2 2 1 0 1 0 2 2 1 0 0 0 2 0 2 2 2 1 0 0 2 0 1 2 2 1
 0 1 1 0 2 2 2 1]
預測準確率 : 0.9555555555555556
